version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_USER: postgres
      POSTGRES_DB: maps
    ports:
      - "5432:5432"
  redis:
    image: redis:7.0.8-alpine

volumes:
  postgres-db:
    driver: local